from pathlib import Path

p=Path('index.html')
s=p.read_text(encoding='utf-8')

def once(old,new,label):
    global s
    n=s.count(old)
    if n!=1:
        raise SystemExit(f'{label}: expected 1 match, found {n}')
    s=s.replace(old,new,1)

# Compact top-bar match control styling.
once('''  #topTimer{\n    margin-left:auto;display:flex;align-items:center;gap:10px;white-space:nowrap;\n    padding-left:10px\n  }\n  #topTimerClock{font-size:22px;font-weight:800;min-width:68px;text-align:right}\n''','''  #topTimer{\n    margin-left:auto;display:flex;align-items:center;gap:8px;white-space:nowrap;\n    padding-left:10px\n  }\n  #topMatchControls{display:none;align-items:center;gap:6px;flex:0 0 auto}\n  #topMatchControls button{\n    width:34px;height:34px;min-width:34px;padding:0;display:grid;place-items:center;border-radius:8px\n  }\n  #topMatchControls button svg{\n    width:17px;height:17px;display:block;stroke:currentColor;fill:none;stroke-width:2.1;\n    stroke-linecap:round;stroke-linejoin:round;pointer-events:none\n  }\n  #topMatchControls #startMatchBtn{background:#6a5720;border-color:#8c7430;color:#fff}\n  #topMatchControls #pauseMatchBtn{background:#29323e;border-color:#3a4553;color:#f5f7fa}\n  #topMatchControls #resetMatchBtn{background:#4a2427;border-color:#6d3438;color:#fff}\n  #topTimerClock{font-size:22px;font-weight:800;min-width:68px;text-align:right}\n''','top match control styles')

# Slight mobile tightening for the new icon controls.
once('''    #topTimerSub{display:none}\n    #topEconomy{padding:5px 7px;gap:4px}\n''','''    #topTimerSub{display:none}\n    #topMatchControls{gap:4px}\n    #topMatchControls button{width:32px;height:32px;min-width:32px}\n    #topEconomy{padding:5px 7px;gap:4px}\n''','mobile top controls')

# Move the existing match control IDs into the top timer group so existing handlers still apply.
once('''  <div id="roomTopStatus">Offline</div>\n  <div id="topTimer">\n    <div>\n      <div id="topTimerClock">00:00</div>\n      <div id="topTimerSub">Match not started</div>\n    </div>\n  </div>\n''','''  <div id="roomTopStatus">Offline</div>\n  <div id="topTimer">\n    <div id="topMatchControls" aria-label="Match controls">\n      <button id="resetMatchBtn" class="danger" type="button" title="Reset match" aria-label="Reset match" style="display:none">\n        <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 4v6h6"/><path d="M5.6 15a8 8 0 1 0 .9-7.2L4 10"/></svg>\n      </button>\n      <button id="startMatchBtn" class="primary" type="button" title="Start match" aria-label="Start match">\n        <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 5v14l11-7Z"/></svg>\n      </button>\n      <button id="pauseMatchBtn" type="button" title="Pause match" aria-label="Pause match" style="display:none">\n        <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 5v14M15 5v14"/></svg>\n      </button>\n    </div>\n    <div>\n      <div id="topTimerClock">00:00</div>\n      <div id="topTimerSub">Match not started</div>\n    </div>\n  </div>\n''','top control markup')

# Remove the large Game-page Match controls card, retaining hidden state targets used by existing render code.
once('''      <section id="matchControlSection" class="compactSection">\n        <h3>Match controls</h3>\n        <div id="matchTimer" style="display:none">00:00</div>\n        <div class="row">\n          <button class="primary" id="startMatchBtn">Start match</button>\n          <button id="pauseMatchBtn" disabled>Pause</button>\n        </div>\n        <button class="danger" id="resetMatchBtn" style="margin-top:8px">Reset match</button>\n        <div id="timerStatus" class="miniStatus">Start the match when everyone is ready.</div>\n      </section>\n''','''      <div id="matchTimer" style="display:none">00:00</div>\n      <div id="timerStatus" style="display:none">Start the match when everyone is ready.</div>\n''','remove match control card')

# Dashboard no longer tries to show/hide the removed card.
once('''  const controls=document.getElementById("matchControlSection"),points=document.getElementById("seekerPointsSection"),qSection=document.getElementById("questionNextSection"),qStatus=document.getElementById("gameQuestionStatus"),qNext=document.getElementById("gameQuestionNext");\n''','''  const points=document.getElementById("seekerPointsSection"),qSection=document.getElementById("questionNextSection"),qStatus=document.getElementById("gameQuestionStatus"),qNext=document.getElementById("gameQuestionNext");\n''','dashboard controls ref')
once('''  controls.style.display=connected&&!!window.BigWalkRooms?.isHost?.()?"block":"none";\n  points.style.display="none";qSection.style.display=isSeeker?"block":"none";\n''','''  points.style.display="none";qSection.style.display=isSeeker?"block":"none";\n''','dashboard controls visibility')

# Add the hide-end audio cue.
once('''  else if(name==="cooldownReady"){tone(523,.00,.10,.65,"triangle");tone(784,.08,.18,.75,"sine");}\n  else if(name==="relocationStart"){tone(220,.00,.16,.9,"square");tone(165,.19,.16,.85,"square");tone(220,.38,.22,.95,"square");}\n''','''  else if(name==="cooldownReady"){tone(523,.00,.10,.65,"triangle");tone(784,.08,.18,.75,"sine");}\n  else if(name==="hidingEnded"){tone(392,.00,.10,.55,"triangle");tone(587,.09,.12,.7,"triangle");tone(880,.20,.27,.9,"sine");}\n  else if(name==="relocationStart"){tone(220,.00,.16,.9,"square");tone(165,.19,.16,.85,"square");tone(220,.38,.22,.95,"square");}\n''','hiding ended tone')
once('''  cooldownReady:{kind:"question",title:"Questions ready",detail:"The global question cooldown has ended."},\n  relocationStart:{kind:"relocation",title:"Forced relocation",detail:"Move to a new legal hiding area before time runs out."},\n''','''  cooldownReady:{kind:"question",title:"Questions ready",detail:"The global question cooldown has ended."},\n  hidingEnded:{kind:"match",title:"Hiding time ended",detail:"The hiding phase is over. Normal play is now active."},\n  relocationStart:{kind:"relocation",title:"Forced relocation",detail:"Move to a new legal hiding area before time runs out."},\n''','hiding ended cue metadata')

# Track and fire hiding-phase transition. Require the match to still be running so reset/pause cannot fake the cue.
once('''    key:audioContextKey(),running:roomModeConnected()?roomMatchRunning():matchRunning,sec,unlockCount,\n    cooldownActive:!testingUnlockOverride&&(Number(questionCooldownUntil||0)-sec)>.01,\n''','''    key:audioContextKey(),running:roomModeConnected()?roomMatchRunning():matchRunning,sec,unlockCount,\n    hidingActive:(roomModeConnected()?roomMatchRunning():matchRunning)&&Number(hidingSettings.duration||0)>0&&sec<Number(hidingSettings.duration||0),\n    cooldownActive:!testingUnlockOverride&&(Number(questionCooldownUntil||0)-sec)>.01,\n''','capture hiding phase')
once('''  if(now.running&&now.unlockCount>prev.unlockCount)triggerGameCue("questionUnlock");\n  if(prev.cooldownActive&&!now.cooldownActive)triggerGameCue("cooldownReady");\n''','''  if(prev.hidingActive&&!now.hidingActive&&now.running)triggerGameCue("hidingEnded");\n  if(now.running&&now.unlockCount>prev.unlockCount)triggerGameCue("questionUnlock");\n  if(prev.cooldownActive&&!now.cooldownActive)triggerGameCue("cooldownReady");\n''','hiding transition cue')

# Rewrite match control state for icon buttons. Host-only, and Reset appears only while paused after a match has begun.
once('''function syncMatchControlButtons(){\n  const connected=roomModeConnected();\n  const canControl=!connected || !!window.BigWalkRooms?.canControlMatch?.();\n  const start=document.getElementById("startMatchBtn"),pause=document.getElementById("pauseMatchBtn"),reset=document.getElementById("resetMatchBtn");\n  const elapsed=currentMatchSeconds();\n  if(matchRunning){\n    start.textContent="Running";start.disabled=true;pause.disabled=!canControl;\n  }else if(elapsed>0.01){\n    start.textContent="Resume";start.disabled=!canControl;pause.disabled=true;\n  }else{\n    start.textContent="Start match";start.disabled=!canControl;pause.disabled=true;\n  }\n  reset.disabled=connected&&!canControl;\n}\n''','''function syncMatchControlButtons(){\n  const connected=roomModeConnected();\n  const canControl=!connected || !!window.BigWalkRooms?.canControlMatch?.();\n  const dock=document.getElementById("topMatchControls"),start=document.getElementById("startMatchBtn"),pause=document.getElementById("pauseMatchBtn"),reset=document.getElementById("resetMatchBtn");\n  const elapsed=currentMatchSeconds(),paused=!matchRunning&&elapsed>0.01;\n  if(dock)dock.style.display=connected&&canControl?"flex":"none";\n  if(matchRunning){\n    start.style.display="none";pause.style.display="grid";reset.style.display="none";\n    pause.disabled=!canControl;pause.title="Pause match";pause.setAttribute("aria-label","Pause match");\n  }else{\n    start.style.display="grid";pause.style.display="none";reset.style.display=paused?"grid":"none";\n    start.disabled=!canControl;start.title=paused?"Resume match":"Start match";start.setAttribute("aria-label",paused?"Resume match":"Start match");\n    reset.disabled=!canControl;\n  }\n}\n''','sync icon match controls')

# Keep top controls synchronized on every render.
once('''  updateQuestionLocks();updateMilestones();updateRuleTimes();updateSeekerPointsDisplay();updateGameDashboard();updateTopRoleBadge();updateTopEconomy();updateRoomChrome();\n\n  const status=document.getElementById("timerStatus"),topSub=document.getElementById("topTimerSub"),hiderView=isRoomHider();\n''','''  updateQuestionLocks();updateMilestones();updateRuleTimes();updateSeekerPointsDisplay();updateGameDashboard();updateTopRoleBadge();updateTopEconomy();updateRoomChrome();syncMatchControlButtons();\n\n  const status=document.getElementById("timerStatus"),topSub=document.getElementById("topTimerSub"),hiderView=isRoomHider();\n''','render top controls sync')

# Local reset no longer mutates button text; sync function owns the icon state.
once('''  document.getElementById("startMatchBtn").textContent="Start match";\n  document.getElementById("startMatchBtn").disabled=false;\n  document.getElementById("pauseMatchBtn").disabled=true;\n''','''  syncMatchControlButtons();\n''','local reset icon state')

# Local start/pause handlers likewise avoid replacing SVG contents.
once('''  matchRunning=true;matchLastTick=performance.now();\n  document.getElementById("startMatchBtn").textContent="Running";\n  document.getElementById("startMatchBtn").disabled=true;\n  document.getElementById("pauseMatchBtn").disabled=false;renderMatchTimer();\n''','''  matchRunning=true;matchLastTick=performance.now();\n  syncMatchControlButtons();renderMatchTimer();\n''','local start icon state')
once('''  tickMatchTimer();matchRunning=false;matchLastTick=null;\n  document.getElementById("startMatchBtn").textContent="Resume";\n  document.getElementById("startMatchBtn").disabled=false;\n  document.getElementById("pauseMatchBtn").disabled=true;renderMatchTimer();\n''','''  tickMatchTimer();matchRunning=false;matchLastTick=null;\n  syncMatchControlButtons();renderMatchTimer();\n''','local pause icon state')

# Changelog entry.
once('''    <div id="view-changelog" class="panelView">\n      <div class="panelHeader"><h2>Changelog</h2><button class="closePanel">Hide</button></div>\n\n''','''    <div id="view-changelog" class="panelView">\n      <div class="panelHeader"><h2>Changelog</h2><button class="closePanel">Hide</button></div>\n\n      <div class="changeEntry">\n        <h4>v1.3.0 preview — Match control polish</h4>\n        <ul>\n          <li>Moved host match controls into compact Play / Pause / Reset icons beside the match timer.</li>\n          <li>Reset appears only while a started match is paused.</li>\n          <li>Added a visual and audio cue when hiding time ends.</li>\n        </ul>\n      </div>\n''','changelog entry')

p.write_text(s,encoding='utf-8')
