from pathlib import Path
import re

p=Path('index.html')
s=p.read_text(encoding='utf-8')

def once(old,new,label):
    global s
    count=s.count(old)
    if count!=1:
        raise SystemExit(f'{label}: expected 1 match, found {count}')
    s=s.replace(old,new,1)

def sub_once(pattern,repl,label,flags=0):
    global s
    s2,n=re.subn(pattern,repl,s,count=1,flags=flags)
    if n!=1:
        raise SystemExit(f'{label}: expected 1 regex match, found {n}')
    s=s2

# ---------- CSS: collapsible questions, top economy, visual cue ----------
once('''  .questionCard .lockNotice{padding:6px 7px;font-size:11px;margin-bottom:6px}\n  #topRoomActions{display:none;align-items:center;gap:6px;flex:0 0 auto}\n''','''  .questionCard .lockNotice{padding:6px 7px;font-size:11px;margin-bottom:6px}\n  .questionCardToggle{\n    appearance:none;width:100%;border:0;background:transparent!important;color:var(--text);padding:1px 0 4px;\n    display:flex;align-items:center;justify-content:space-between;gap:10px;text-align:left;font-size:16px;font-weight:900;cursor:pointer\n  }\n  .questionCardToggle:hover{color:#fff}\n  .questionChevron{font-size:16px;color:var(--muted);transition:transform .16s ease}\n  .questionCard:not(.collapsed) .questionChevron{transform:rotate(180deg)}\n  .questionCard.collapsed .questionCardBody{display:none}\n  .questionCard.locked .questionCardBody{display:none!important}\n  .questionCard.locked .questionCardToggle{opacity:1}\n  #topEconomy{\n    display:none;position:absolute;left:50%;transform:translateX(-50%);align-items:baseline;gap:7px;\n    white-space:nowrap;padding:6px 10px;border:1px solid #435064;border-radius:999px;background:#171d25;z-index:3\n  }\n  #topEconomyValue{font-size:13px;font-weight:900}\n  #topEconomyRate{font-size:10px;font-weight:750;color:var(--muted)}\n  #topEconomy.hider{border-color:#6e4f7d;background:#281b30;color:#efceff}\n  #topEconomy.seeker{border-color:#4e6480;background:#172535;color:#cbe3ff}\n  #gameCueToast{\n    display:none;position:fixed;top:70px;left:50%;transform:translate(-50%,-10px) scale(.97);z-index:95;\n    min-width:240px;max-width:min(420px,calc(100vw - 28px));padding:10px 13px;border:1px solid #526174;border-radius:11px;\n    background:rgba(20,26,34,.98);box-shadow:0 12px 34px rgba(0,0,0,.42);pointer-events:none;opacity:0\n  }\n  #gameCueToast.show{display:block;animation:gameCueIn .22s ease-out forwards,gameCuePulse .55s ease-out .22s 1}\n  #gameCueTitle{font-size:13px;font-weight:900}\n  #gameCueDetail{font-size:11px;color:#c5ced9;margin-top:2px;line-height:1.3}\n  #gameCueToast.question{border-color:#4e7a62;background:rgba(23,42,32,.98)}\n  #gameCueToast.relocation{border-color:#8b5f91;background:rgba(42,27,47,.98)}\n  #gameCueToast.mission{border-color:#765aae;background:rgba(38,27,54,.98)}\n  #gameCueToast.match{border-color:#79642d;background:rgba(43,37,20,.98)}\n  @keyframes gameCueIn{to{opacity:1;transform:translate(-50%,0) scale(1)}}\n  @keyframes gameCuePulse{0%,100%{box-shadow:0 12px 34px rgba(0,0,0,.42)}50%{box-shadow:0 0 0 4px rgba(255,255,255,.08),0 12px 34px rgba(0,0,0,.42)}}\n  #topRoomActions{display:none;align-items:center;gap:6px;flex:0 0 auto}\n''','question/top cue css')

# Old locked-card direct-child collapse rule conflicts with the new body wrapper.
once('''  .questionCard.locked>label,.questionCard.locked>select,.questionCard.locked>input,.questionCard.locked>button,.questionCard.locked>p,.questionCard.locked>.validation,.questionCard.locked>div:not(.questionCost):not(.lockNotice){display:none!important}\n  .questionCard.locked{padding-bottom:9px}\n''','''  .questionCard.locked{padding-bottom:9px}\n''','replace old locked question collapse css')

# Mobile top economy remains centered but gets leaner.
once('''    #topTimerSub{display:none}\n    #roomConnected{right:8px;top:52px}\n''','''    #topTimerSub{display:none}\n    #topEconomy{padding:5px 7px;gap:4px}\n    #topEconomyValue{font-size:11px}\n    #topEconomyRate{font-size:9px}\n    #roomConnected{right:8px;top:52px}\n''','mobile economy css')

# ---------- Top bar economy + visual cue ----------
once('''  </div>\n  <div id="roomTopStatus">Offline</div>\n  <div id="topTimer">\n''','''  </div>\n  <div id="topEconomy"><span id="topEconomyValue">0</span><span id="topEconomyRate"></span></div>\n  <div id="roomTopStatus">Offline</div>\n  <div id="topTimer">\n''','top economy markup')

once('''<div id="updateBanner">\n  <span id="updateBannerText">A newer version is available.</span>\n  <button id="reloadLatestBtn">Reload latest</button>\n</div>\n\n<div id="app">\n''','''<div id="updateBanner">\n  <span id="updateBannerText">A newer version is available.</span>\n  <button id="reloadLatestBtn">Reload latest</button>\n</div>\n<div id="gameCueToast" role="status" aria-live="polite">\n  <div id="gameCueTitle"></div>\n  <div id="gameCueDetail"></div>\n</div>\n\n<div id="app">\n''','game cue markup')

# Keep seeker-points data in DOM for accounting, but move the visible balance to the top bar.
once('''      <section id="seekerPointsSection" class="compactSection">\n''','''      <section id="seekerPointsSection" class="compactSection" style="display:none">\n''','hide old seeker points card')

# Power charges now live in top bar; preserve hidden element for existing mission code.
once('''        <div class="metric"><b>Power Charges</b><span class="powerCharge" id="hiderPowerCharges">0</span></div>\n''','''        <div class="metric" style="display:none"><b>Power Charges</b><span class="powerCharge" id="hiderPowerCharges">0</span></div>\n''','hide mission charge row')

# Remove redundant relocation status row but preserve the id for compatibility.
once('''        <div class="metric"><b>Status</b><span id="relocationStatus">Relocation in progress</span></div>\n''','''        <span id="relocationStatus" style="display:none"></span>\n''','remove relocation status row')

# Remove the schedule reference section from Rules entirely.
sub_once(r'''\n      <section>\n        <h3>Current question schedule</h3>.*?\n      </section>\n''','\n','remove rules question schedule',re.S)

# Add pass changelog above the previous pass.
once('''      <div class="changeEntry">\n        <h4>v1.3.0 preview — Room + question cleanup</h4>\n''','''      <div class="changeEntry">\n        <h4>v1.3.0 preview — Gameplay clarity pass</h4>\n        <ul>\n          <li>Made question cards collapsible and moved role economy into the center of the top bar.</li>\n          <li>Added animated visual notifications that identify gameplay sounds as they occur.</li>\n          <li>Relocation scheduling and normal relocation activity are now private to the Hider; Seekers only see intentional reveal effects.</li>\n          <li>Question unlock/cooldown cues are Seeker-only and relocation cues are Hider-only.</li>\n          <li>Fixed Settings number fields being overwritten while a user is editing an unapplied draft.</li>\n        </ul>\n      </div>\n      <div class="changeEntry">\n        <h4>v1.3.0 preview — Room + question cleanup</h4>\n''','pass3 changelog')

# ---------- Settings draft protection state ----------
once('''let questionCooldownUntil=0;\nlet seekerPointsSpent=0;\nconst pointsPerMinute=1;\n''','''let questionCooldownUntil=0;\nlet seekerPointsSpent=0;\nconst pointsPerMinute=1;\nconst settingsDirtyInputs=new Set();\n''','settings dirty state')

# ---------- Cue system ----------
# Insert after playGameSound, before audioContextKey.
anchor='''function audioContextKey(){\n  return roomModeConnected()?`room:${window.BigWalkRooms?.getRoomCode?.()||"connected"}`:"local";\n}\n'''
if s.count(anchor)!=1:
    raise SystemExit(f'audio context anchor: expected 1 match, found {s.count(anchor)}')
insert='''let gameCueTimer=null;\nconst GAME_CUE_META={\n  questionUnlock:{kind:"question",title:"Question unlocked",detail:"A new Seeker question type is available."},\n  cooldownReady:{kind:"question",title:"Questions ready",detail:"The global question cooldown has ended."},\n  relocationStart:{kind:"relocation",title:"Forced relocation",detail:"Move to a new legal hiding area before time runs out."},\n  relocationOvertime:{kind:"relocation",title:"Relocation overtime",detail:"Your overtime reveal has triggered. Keep moving and finish the relocation."},\n  relocationReady:{kind:"relocation",title:"Relocation target reached",detail:"You can press Ready once you have your new hiding spot."},\n  relocationComplete:{kind:"relocation",title:"Relocation complete",detail:"A fresh relocation interval has started."},\n  missionStart:{kind:"mission",title:"Mission started",detail:"Cross the Zone is active."},\n  missionComplete:{kind:"mission",title:"Mission complete",detail:"Power Charge earned."},\n  missionCancel:{kind:"mission",title:"Mission cancelled",detail:"The mission ended without a charge."},\n  matchStart:{kind:"match",title:"Match started",detail:"The hiding phase has begun."},\n  matchPause:{kind:"match",title:"Match paused",detail:"Gameplay timers are paused."},\n  matchResume:{kind:"match",title:"Match resumed",detail:"Gameplay timers are running again."}\n};\nfunction cueAllowedForRole(name){\n  if(!roomModeConnected())return true;\n  const role=roomRole();\n  if(name==="questionUnlock"||name==="cooldownReady")return role==="seeker";\n  if(name.startsWith("relocation"))return role==="hider";\n  if(name.startsWith("mission"))return role==="hider";\n  return true;\n}\nfunction showGameCue(name,detailOverride=""){\n  const meta=GAME_CUE_META[name];if(!meta)return;\n  const toast=document.getElementById("gameCueToast"),title=document.getElementById("gameCueTitle"),detail=document.getElementById("gameCueDetail");\n  if(!toast||!title||!detail)return;\n  clearTimeout(gameCueTimer);\n  toast.className=meta.kind;title.textContent=meta.title;detail.textContent=detailOverride||meta.detail;\n  void toast.offsetWidth;toast.classList.add("show");\n  gameCueTimer=setTimeout(()=>{toast.classList.remove("show");setTimeout(()=>{if(!toast.classList.contains("show"))toast.style.display="none";},230);},2700);\n}\nfunction triggerGameCue(name){\n  if(!cueAllowedForRole(name))return;\n  showGameCue(name);\n  playGameSound(name);\n}\n\n'''
s=s.replace(anchor,insert+anchor,1)

# Route event sounds through visible, role-aware cues.
replacements={
'''if(!prev.running&&now.running)playGameSound(now.sec<2?"matchStart":"matchResume");''':'''if(!prev.running&&now.running)triggerGameCue(now.sec<2?"matchStart":"matchResume");''',
'''else if(prev.running&&!now.running&&now.sec>.1)playGameSound("matchPause");''':'''else if(prev.running&&!now.running&&now.sec>.1)triggerGameCue("matchPause");''',
'''if(now.running&&now.unlockCount>prev.unlockCount)playGameSound("questionUnlock");''':'''if(now.running&&now.unlockCount>prev.unlockCount)triggerGameCue("questionUnlock");''',
'''if(prev.cooldownActive&&!now.cooldownActive&&!now.relocationActive)playGameSound("cooldownReady");''':'''if(prev.cooldownActive&&!now.cooldownActive)triggerGameCue("cooldownReady");''',
'''if(!prev.relocationActive&&now.relocationActive)playGameSound("relocationStart");''':'''if(!prev.relocationActive&&now.relocationActive)triggerGameCue("relocationStart");''',
'''if(!prev.relocationOvertime&&now.relocationOvertime)playGameSound("relocationOvertime");''':'''if(!prev.relocationOvertime&&now.relocationOvertime)triggerGameCue("relocationOvertime");''',
'''if(prev.relocationActive&&!now.relocationActive)playGameSound("relocationComplete");''':'''if(prev.relocationActive&&!now.relocationActive)triggerGameCue("relocationComplete");''',
'''if(!prev.relocationReady&&now.relocationReady)playGameSound("relocationReady");''':'''if(!prev.relocationReady&&now.relocationReady)triggerGameCue("relocationReady");''',
'''if(!prev.missionActive&&now.missionActive)playGameSound("missionStart");''':'''if(!prev.missionActive&&now.missionActive)triggerGameCue("missionStart");''',
'''if(prev.missionActive&&!now.missionActive)playGameSound(now.missionLastResult==="completed"?"missionComplete":"missionCancel");''':'''if(prev.missionActive&&!now.missionActive)triggerGameCue(now.missionLastResult==="completed"?"missionComplete":"missionCancel");'''
}
for old,new in replacements.items():
    once(old,new,'cue routing '+old[:25])

# ---------- Question collapsibles + top economy + settings helpers ----------
# Insert before updateGameDashboard.
anchor='''function updateGameDashboard(){\n'''
if s.count(anchor)!=1:
    raise SystemExit('dashboard anchor mismatch')
insert='''function initializeQuestionCollapsibles(){\n  document.querySelectorAll(".questionCard").forEach(section=>{\n    if(section.dataset.collapsibleReady==="1")return;\n    const heading=section.querySelector(":scope > h3"),cost=section.querySelector(":scope > .questionCost"),notice=section.querySelector(":scope > .lockNotice");\n    if(!heading)return;\n    const toggle=document.createElement("button");toggle.type="button";toggle.className="questionCardToggle";toggle.setAttribute("aria-expanded","false");\n    const title=document.createElement("span");title.textContent=heading.textContent;\n    const chevron=document.createElement("span");chevron.className="questionChevron";chevron.textContent="⌄";\n    toggle.append(title,chevron);heading.replaceWith(toggle);\n    const body=document.createElement("div");body.className="questionCardBody";\n    let node=(notice||cost||toggle).nextSibling;\n    while(node){const next=node.nextSibling;body.appendChild(node);node=next;}\n    section.appendChild(body);section.classList.add("collapsed");section.dataset.collapsibleReady="1";\n    toggle.addEventListener("click",()=>{const collapsed=section.classList.toggle("collapsed");toggle.setAttribute("aria-expanded",String(!collapsed));});\n  });\n}\nfunction updateTopEconomy(){\n  const box=document.getElementById("topEconomy"),value=document.getElementById("topEconomyValue"),rate=document.getElementById("topEconomyRate");\n  if(!box||!value||!rate)return;\n  box.classList.remove("hider","seeker");\n  if(!roomModeConnected()){box.style.display="none";return;}\n  const role=roomRole();box.style.display="flex";box.classList.add(role==="hider"?"hider":"seeker");\n  if(role==="hider"){const n=Math.max(0,Number(hiderPowerCharges||0));value.textContent=`⚡ ${n} Power Charge${n===1?"":"s"}`;rate.textContent="";}\n  else{const n=seekerPointsBalance();value.textContent=`${n} Seeker Point${n===1?"":"s"}`;rate.textContent=`${pointsPerMinute}/min`;}\n}\nfunction settingDraftDirty(id){return settingsDirtyInputs.has(id);}\nfunction syncSettingValue(id,value){const el=document.getElementById(id);if(!el||settingDraftDirty(id)||document.activeElement===el)return;if(String(el.value)!==String(value))el.value=String(value);}\nfunction syncSettingChecked(id,value){const el=document.getElementById(id);if(!el||settingDraftDirty(id)||document.activeElement===el)return;el.checked=!!value;}\nfunction clearSettingDraft(ids){for(const id of ids)settingsDirtyInputs.delete(id);}\nfunction bindSettingDraftProtection(){\n  document.querySelectorAll('#view-settings input[type="number"]').forEach(el=>el.addEventListener("input",()=>settingsDirtyInputs.add(el.id)));\n  const linked=document.getElementById("firstQuestionOnHideEnd");if(linked)linked.addEventListener("change",()=>settingsDirtyInputs.add(linked.id));\n}\n\n'''
s=s.replace(anchor,insert+anchor,1)

# Dashboard: old seeker-points card stays hidden; no relocation schedule/activity shown to Seekers.
once('''  const controls=document.getElementById("matchControlSection"),points=document.getElementById("seekerPointsSection"),qSection=document.getElementById("questionNextSection"),qStatus=document.getElementById("gameQuestionStatus"),qNext=document.getElementById("gameQuestionNext"),relocationSection=document.getElementById("relocationGameSection");\n''','''  const controls=document.getElementById("matchControlSection"),points=document.getElementById("seekerPointsSection"),qSection=document.getElementById("questionNextSection"),qStatus=document.getElementById("gameQuestionStatus"),qNext=document.getElementById("gameQuestionNext");\n''','dashboard relocation section ref')
once('''  controls.style.display=connected&&!!window.BigWalkRooms?.isHost?.()?"block":"none";\n  if(relocationSection)relocationSection.style.display=connected?"block":"none";\n  points.style.display=isSeeker?"block":"none";qSection.style.display=isSeeker?"block":"none";\n''','''  controls.style.display=connected&&!!window.BigWalkRooms?.isHost?.()?"block":"none";\n  points.style.display="none";qSection.style.display=isSeeker?"block":"none";\n''','dashboard card visibility')
once('''    else if(relocationState.active){qStatus.textContent="Locked";qNext.textContent="Questions are unavailable during forced relocation.";}\n    else if(questionCooldownActive()){qStatus.textContent=`Cooling down · ${formatApproxDuration(questionCooldownRemaining())}`;qNext.textContent=nextQuestionUnlockInfo(sec)+".";}\n''','''    else if(questionCooldownActive()){qStatus.textContent=`Cooling down · ${formatApproxDuration(questionCooldownRemaining())}`;qNext.textContent=nextQuestionUnlockInfo(sec)+".";}\n''','remove seeker relocation question status')
once('''  const relocationNext=Math.max(0,Number(relocationState.nextAt??relocationSettings.firstAt)-sec);\n  next.textContent=missionState.active?"Relocation · paused":`Next relocation · ${formatApproxDuration(relocationNext)}`;\n  secondary.textContent=isHider?`⚡ ${Math.max(0,Number(hiderPowerCharges||0))} Power Charge${Number(hiderPowerCharges||0)===1?"":"s"}`:isSeeker?`${seekerPointsBalance()} Seeker Point${seekerPointsBalance()===1?"":"s"}`:"—";\n''','''  const relocationNext=Math.max(0,Number(relocationState.nextAt??relocationSettings.firstAt)-sec);\n  if(isHider)next.textContent=missionState.active?"Relocation · paused":`Next relocation · ${formatApproxDuration(relocationNext)}`;\n  else if(isSeeker)next.textContent=questionCooldownActive()?`Questions · ${formatApproxDuration(questionCooldownRemaining())}`:nextQuestionUnlockInfo(sec);\n  else next.textContent="No active match";\n  secondary.textContent=isHider?"Hider":"Seeker";\n''','dashboard next event privacy')
once('''  if(relocationState.active){\n    card.classList.add("urgent");eyebrow.textContent="CURRENT OBJECTIVE";\n''','''  if(relocationState.active&&isHider){\n    card.classList.add("urgent");eyebrow.textContent="CURRENT OBJECTIVE";\n''','hider-only relocation dashboard branch')
once('''    title.textContent=isHider?"Forced relocation":"Hider relocating";\n    if(isHider&&localRelocationPlan&&!localRelocationPlan.invalid&&!localRelocationPlan.skip&&liveMarker){const d=Math.hypot(liveMarker.x-localRelocationPlan.start.x,liveMarker.y-localRelocationPlan.start.y);detail.textContent=`${Math.round(d)} / ${Math.round(localRelocationPlan.target)} units from relocation start.`;}\n    else detail.textContent=isHider?"Move to a legal new hiding area and press Ready when the target is met.":"Questions are locked until the Hider finishes relocating.";\n''','''    title.textContent="Forced relocation";\n    if(localRelocationPlan&&!localRelocationPlan.invalid&&!localRelocationPlan.skip&&liveMarker){const d=Math.hypot(liveMarker.x-localRelocationPlan.start.x,liveMarker.y-localRelocationPlan.start.y);detail.textContent=`${Math.round(d)} / ${Math.round(localRelocationPlan.target)} units from relocation start.`;}\n    else detail.textContent="Move to a legal new hiding area and press Ready when the target is met.";\n''','remove seeker relocation dashboard wording')

# ---------- Relocation card: Hider-only + active-only ----------
once('''  if(!roomModeConnected()||!relocationState.active){section.style.display="none";return;}\n  section.style.display="block";\n''','''  if(!roomModeConnected()||!isRoomHider()||!relocationState.active){section.style.display="none";return;}\n  section.style.display="block";\n''','relocation card visibility')

# The seeker branch in updateRelocationUi is now unreachable; remove its message text anyway so source has no normal seeker relocation UI.
sub_once(r'''    }else\{\n      target\.textContent=`\$\{relocationSettings\.minDistance\} units minimum`;\n      progress\.textContent="Hidden from seekers";\n      if\(remaining>0\)message\.textContent="Questions are locked while the hider relocates\.";\n      else if\(window\.BigWalkRooms\?\.getBuildId\?\.\(\)!==REQUIRED_ROOMS_BUILD_ID\)message\.textContent="Room sync module is out of date — hard refresh this browser\.";\n      else message\.textContent=activeOvertimeReveal\(\)\?"Relocation overtime — the hider's last-known 300-unit-diameter area is revealed in red for 2 minutes\.":"Relocation overtime — waiting for the Hider snapshot…";\n    }\n''','''    }\n''','remove seeker relocation card branch')

# ---------- Questions no longer reveal relocation by locking ----------
sub_once(r'''  if\(roomModeConnected\(\)&&relocationState\.active\)\{\n    clock\.textContent="RELOCATION";clock\.classList\.add\("waiting"\);\n    status\.textContent="Questions are locked while the Hider relocates\.";\n  }else if\(testingUnlockOverride\)\{''','''  if(testingUnlockOverride){''','cooldown relocation privacy')
once('''  const cooldown=questionCooldownActive();\n  const relocationLock=roomModeConnected()&&!!relocationState.active;\n  const roomReadOnly=roomModeConnected()&&!roomCanEditSharedGame();\n  const locked=!unlocked || cooldown || relocationLock || roomReadOnly;\n\n  section.classList.toggle("locked",locked);\n  section.querySelectorAll("input,select,button").forEach(el=>el.disabled=locked);\n''','''  const cooldown=questionCooldownActive();\n  const roomReadOnly=roomModeConnected()&&!roomCanEditSharedGame();\n  const locked=!unlocked || cooldown || roomReadOnly;\n\n  section.classList.toggle("locked",locked);\n  if(locked){section.classList.add("collapsed");section.querySelector(".questionCardToggle")?.setAttribute("aria-expanded","false");}\n  section.querySelectorAll("input,select,button:not(.questionCardToggle)").forEach(el=>el.disabled=locked);\n''','question lock logic privacy/collapse')
once('''  }else if(relocationLock){\n    notice.textContent="Locked during forced relocation.";\n  }else if(cooldown){\n''','''  }else if(cooldown){\n''','remove relocation lock notice')

# ---------- Top subtext must not reveal relocation to Seekers ----------
once('''  if(hidingTimeRemaining()>.01)topSub.textContent="Hiding time";\n  else if(roomModeConnected()&&relocationState.active)topSub.textContent="Forced relocation active";\n  else if(roomModeConnected()&&missionState.active)topSub.textContent="Hider mission active";\n''','''  if(hidingTimeRemaining()>.01)topSub.textContent="Hiding time";\n  else if(roomModeConnected()&&relocationState.active&&isRoomHider())topSub.textContent="Forced relocation active";\n  else if(roomModeConnected()&&missionState.active)topSub.textContent=roomRole()==="hider"?"Hider mission active":"Match running";\n''','top sub relocation privacy')

# ---------- Settings draft protection ----------
once('''function updateRelocationSettingsInputs(){\n  const ids={relocationFirstMinutes:relocationSettings.firstAt/60,relocationIntervalMinutes:relocationSettings.interval/60,relocationWindowMinutes:relocationSettings.window/60,relocationMinDistance:relocationSettings.minDistance,relocationSkipBelow:relocationSettings.skipBelow};\n  for(const [id,value] of Object.entries(ids)){const el=document.getElementById(id);if(el)el.value=value;}\n}\n''','''function updateRelocationSettingsInputs(){\n  const ids={relocationFirstMinutes:relocationSettings.firstAt/60,relocationIntervalMinutes:relocationSettings.interval/60,relocationWindowMinutes:relocationSettings.window/60,relocationMinDistance:relocationSettings.minDistance,relocationSkipBelow:relocationSettings.skipBelow};\n  for(const [id,value] of Object.entries(ids))syncSettingValue(id,value);\n}\n''','protect relocation settings sync')
once('''  document.getElementById("hideTimeMinutes").value=hidingSettings.duration/60;\n  document.getElementById("firstQuestionOnHideEnd").checked=hidingSettings.firstQuestionOnEnd!==false;\n  document.getElementById("firstUnlockMinutes").value=unlockTimes.grid/60;\n  document.getElementById("gridUnlockMinutes").value=unlockTimes.grid/60;\n  document.getElementById("nearestUnlockMinutes").value=unlockTimes.nearest/60;\n  document.getElementById("towerRadiusUnlockMinutes").value=unlockTimes.towerRadius/60;\n  document.getElementById("landmarkUnlockMinutes").value=unlockTimes.landmark/60;\n  document.getElementById("markerUnlockMinutes").value=unlockTimes.marker/60;\n  document.getElementById("questionCooldownMinutes").value=questionCooldownSeconds/60;\n''','''  syncSettingValue("hideTimeMinutes",hidingSettings.duration/60);\n  syncSettingChecked("firstQuestionOnHideEnd",hidingSettings.firstQuestionOnEnd!==false);\n  syncSettingValue("firstUnlockMinutes",unlockTimes.grid/60);\n  syncSettingValue("gridUnlockMinutes",unlockTimes.grid/60);\n  syncSettingValue("nearestUnlockMinutes",unlockTimes.nearest/60);\n  syncSettingValue("towerRadiusUnlockMinutes",unlockTimes.towerRadius/60);\n  syncSettingValue("landmarkUnlockMinutes",unlockTimes.landmark/60);\n  syncSettingValue("markerUnlockMinutes",unlockTimes.marker/60);\n  syncSettingValue("questionCooldownMinutes",questionCooldownSeconds/60);\n''','protect timing settings sync')
once('''  for(const [id,key] of Object.entries(ids)){const el=document.getElementById(id);if(el)el.value=String(questionCosts[key]);}\n}\n''','''  for(const [id,key] of Object.entries(ids))syncSettingValue(id,questionCosts[key]);\n}\n''','protect cost settings sync')

# Quick builder values are intentional drafts; protect them from remote sync until Apply.
once('''  ["gridUnlockMinutes","nearestUnlockMinutes","towerRadiusUnlockMinutes","landmarkUnlockMinutes","markerUnlockMinutes"].forEach((id,i)=>document.getElementById(id).value=vals[i]);\n  document.getElementById("scheduleSummary").textContent=`Preview: hiding ${formatTime(hide*60)} · questions ${vals.map(m=>formatTime(m*60)).join(" → ")}`;\n''','''  ["gridUnlockMinutes","nearestUnlockMinutes","towerRadiusUnlockMinutes","landmarkUnlockMinutes","markerUnlockMinutes"].forEach((id,i)=>{document.getElementById(id).value=vals[i];settingsDirtyInputs.add(id);});\n  document.getElementById("scheduleSummary").textContent=`Preview: hiding ${formatTime(hide*60)} · questions ${vals.map(m=>formatTime(m*60)).join(" → ")}`;\n''','protect builder drafts')

# Existing hide-control listeners get explicit draft propagation for linked fields.
once('''document.getElementById("hideTimeMinutes").addEventListener("input",syncHideTimeControls);\ndocument.getElementById("firstQuestionOnHideEnd").addEventListener("change",syncHideTimeControls);\n''','''document.getElementById("hideTimeMinutes").addEventListener("input",()=>{syncHideTimeControls();if(document.getElementById("firstQuestionOnHideEnd").checked){settingsDirtyInputs.add("firstUnlockMinutes");settingsDirtyInputs.add("gridUnlockMinutes");}});\ndocument.getElementById("firstQuestionOnHideEnd").addEventListener("change",()=>{syncHideTimeControls();settingsDirtyInputs.add("firstUnlockMinutes");settingsDirtyInputs.add("gridUnlockMinutes");});\n''','linked hide draft listeners')

# Clear draft flags only after successful Apply so synced room state can resume updating those controls.
once('''  hidingSettings={duration:hideMinutes*60,firstQuestionOnEnd:linked};\n  unlockTimes={grid:vals[0]*60,nearest:vals[1]*60,towerRadius:vals[2]*60,landmark:vals[3]*60,marker:vals[4]*60};\n  questionCooldownSeconds=cooldownMinutes*60;\n  updateScheduleInputs();renderMatchTimer();notifyRoomGameStateChanged();\n''','''  hidingSettings={duration:hideMinutes*60,firstQuestionOnEnd:linked};\n  unlockTimes={grid:vals[0]*60,nearest:vals[1]*60,towerRadius:vals[2]*60,landmark:vals[3]*60,marker:vals[4]*60};\n  questionCooldownSeconds=cooldownMinutes*60;\n  clearSettingDraft(["hideTimeMinutes","firstQuestionOnHideEnd","firstUnlockMinutes","unlockIntervalMinutes","gridUnlockMinutes","nearestUnlockMinutes","towerRadiusUnlockMinutes","landmarkUnlockMinutes","markerUnlockMinutes","questionCooldownMinutes"]);\n  updateScheduleInputs();renderMatchTimer();notifyRoomGameStateChanged();\n''','clear timing draft on apply')
once('''  questionCosts=nextCosts;updateQuestionCostInputs();updateQuestionEconomy();notifyRoomGameStateChanged();\n''','''  questionCosts=nextCosts;clearSettingDraft(Object.keys(ids));updateQuestionCostInputs();updateQuestionEconomy();notifyRoomGameStateChanged();\n''','clear cost drafts on apply')
once('''  relocationSettings={firstAt:first*60,interval:interval*60,window:windowMin*60,minDistance,skipBelow};\n  if(!relocationState.active&&!missionState.active){relocationState.nextAt=relocationState.index===0?relocationSettings.firstAt:currentMatchSeconds()+relocationSettings.interval;}\n  resetLocalRelocationPlan();renderMatchTimer();notifyRoomGameStateChanged();\n''','''  relocationSettings={firstAt:first*60,interval:interval*60,window:windowMin*60,minDistance,skipBelow};\n  if(!relocationState.active&&!missionState.active){relocationState.nextAt=relocationState.index===0?relocationSettings.firstAt:currentMatchSeconds()+relocationSettings.interval;}\n  clearSettingDraft(["relocationFirstMinutes","relocationIntervalMinutes","relocationWindowMinutes","relocationMinDistance","relocationSkipBelow"]);\n  resetLocalRelocationPlan();updateRelocationSettingsInputs();renderMatchTimer();notifyRoomGameStateChanged();\n''','clear relocation drafts on apply')

# ---------- Render economy and initialize collapsibles ----------
once('''  updateQuestionLocks();updateMilestones();updateRuleTimes();updateSeekerPointsDisplay();updateGameDashboard();updateTopRoleBadge();updateRoomChrome();\n''','''  updateQuestionLocks();updateMilestones();updateRuleTimes();updateSeekerPointsDisplay();updateGameDashboard();updateTopRoleBadge();updateTopEconomy();updateRoomChrome();\n''','render top economy')

# Test sound also demonstrates the visual meaning.
once('''document.getElementById("testSoundBtn").onclick=()=>playGameSound("questionUnlock");\n''','''document.getElementById("testSoundBtn").onclick=()=>{showGameCue("questionUnlock","Example visual cue for a gameplay sound.");playGameSound("questionUnlock");};\n''','test sound visual cue')

# Initialization binds collapsibles and draft protection once.
once('''  populate();updateMarkerPanel();updateRulerPanel();updateGridInputRules();updateScheduleInputs();\n  setToolMode("pan");renderMatchTimer();startTimerLoop();draw();fitMap();\n''','''  populate();initializeQuestionCollapsibles();bindSettingDraftProtection();updateMarkerPanel();updateRulerPanel();updateGridInputRules();updateScheduleInputs();updateQuestionCostInputs();updateRelocationSettingsInputs();\n  setToolMode("pan");renderMatchTimer();startTimerLoop();draw();fitMap();\n''','initialize pass3 systems')

p.write_text(s,encoding='utf-8')
