<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>BigWalkHideSeek.Loader</AssemblyName>
    <RootNamespace>BigWalkHideSeek.Loader</RootNamespace>
    <Version>0.1.1</Version>
    <AssemblyVersion>0.1.1.0</AssemblyVersion>
    <FileVersion>0.1.1.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx.Core">
      <HintPath>$(ProfilePath)\BepInEx\core\BepInEx.Core.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Unity.Common">
      <HintPath>$(ProfilePath)\BepInEx\core\BepInEx.Unity.Common.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>$(ProfilePath)\BepInEx\core\BepInEx.Unity.IL2CPP.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
